version: 0.2

phases:
  build:
    commands:
      - pip install -r requirements.txt -t ./build  # Install dependencies to a 'build' directory
      - cd build
      - zip -r lambda-package.zip .  # Create a ZIP file containing the Lambda function code and dependencies
artifacts:
  files: lambda-package.zip
